
export const columnsObject = {
    id:{
        uiName:"ID",
        dataType:"Number",
        isSortable:false,
        isFilterable:false,
        isSearchable:false,
        filterId:1
    },
    configurationItem:{
        uiName:"Configuration Item",
        dataType:"String",
        isSortable:true,
        isFilterable:true,
        isSearchable:true,
        filterId:2
    },
    region:{
        uiName:"Region",
        dataType:"String",
        isSortable:true,
        isFilterable:true,
        isSearchable:true,
        filterId:3,
    },
    subRegion:{
        uiName:"Sub Region",
        dataType:"String",
        isSortable:true,
        isFilterable:true,
        isSearchable:true,
        filterId:4
    },
    status:{
        uiName:"Status",
        dataType:"String",
        isSortable:true,
        isFilterable:true,
        isSearchable:true,
        filterId:5
    },
    priority:{
        uiName:"Priority",
        dataType:"String",
        isSortable:true,
        isFilterable:true,
        isSearchable:true,
        filterId:6
    }
}
